- vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsController.kt
- vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsFragment.kt
- vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsViewState.kt
- vector/src/main/java/im/vector/app/features/roomdirectory/RoomDirectoryAction.kt
- vector/src/main/java/im/vector/app/features/roomdirectory/RoomDirectoryViewModel.kt
- vector/src/main/java/im/vector/app/features/roomdirectory/picker/RoomDirectoryPickerFragment.kt
- vector/src/main/res/layout/fragment_public_rooms.xml
> [Public rooms] - List all the forums from the rooms directory

- vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
> Automatically give user consent to identity server policy

- changelog.d/389.bugfix
- vector/build.gradle
- vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderGroup.kt
- vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderSpace.kt
- vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
- vector/src/main/res/xml/vector_settings_preferences.xml
#389 
This was caused by the use of Spaces or low priority tags. It might require cleaning the application data after updating the application.
> [Room list] Fix potential missing rooms

- changelog.d/402.bugfix
- vector/src/fdroid/withpinning/res/xml/network_security_config.xml
- vector/src/gplay/java/im/vector/app/push/fcm/NotificationTroubleshootTestManagerFactory.kt
- vector/src/gplay/withpinning/res/xml/network_security_config.xml
- vector/src/withpinning/res/xml/network_security_config.xml
#402 
The FCM token could not be retrieved because of the pinning restriction which does not allow the system certificates. These certificates are required to request the FCM token through the firebase API. This PR allows the use of the system certificates for the firebase domain only.
This PR also hide the "Test push" step from the "Troubleshoot Notifications" screen. This step was triggering a notification using the push server `notify` endpoint. The push server has been moved to a new internal sygnal server which is only accessible from the Synapse. This step will be hidden while there is no equivalent public API to trigger a notification.
> Fix the FCM token error

- changelog.d/479.bugfix
- vector/src/main/java/fr/gouv/tchap/core/utils/TchapUtils.kt
- vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItem.kt
Added a dedicated method to compute the room name from a display name. The domain part is now removed only for DM, the original display name is kept for the other room types.
Room names containing brackets are cropped because the Tchap domain part is removed from the display name in the room list. All the rooms are impacted (whether the room type is a DM or not). The removing of the domain part should only be applied for DMs.
Before:
After:
- Create or join a room containing brackets (for example `test [room] type`
- Test without the fix -> only the left part is displayed in the room list `room `
- Test after the fix -> all the room name is displayed `test [room] type`
- Verify the other room or user names have not been impacted (for each room type): in the room list, the room details and …
> Fix room name containing brackets cropped

- changelog.d/481.bugfix
- vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
#481 
We don't scroll to the position 0 when a room is opened/created
https://user-images.githubusercontent.com/15031750/157635104-dea9c061-bf9a-4c4b-bcdc-92c8c0291531.mov
- Open a room, no scroll before the opening.
- Create a room, no scroll before the opening
> Room list is automatically scrolled to the top after opening a room

- .github/workflows/build.yml
- changelog.d/517.bugfix
- towncrier.toml
- vector/build.gradle
- vector/src/withoutpinning/res/xml/network_security_config.xml
#524 
This version fix pinning issues on some specific secure devices using the fdroid version of Tchap.
The fix is already included in Tchap v2.1.0, see #518
> Hotfix version 2.0.4

- .github/workflows/nightly.yml
- TCHAP_CHANGES.md
- changelog.d/342.improvements
- changelog.d/497.misc
- changelog.d/520.bugfix
- changelog.d/521.bugfix
Nightly tests coming from Element introduced by #538 have been disabled for this release, especially because of issues related to the setup of synapse.
> Release Tchap-Android-v2.2.0

- changelog.d/542.misc
- vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
- vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
- vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt
- vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderGroup.kt
- vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilderSpace.kt
- vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
- vector/src/main/res/menu/home.xml
#542 
- [] Changes has been tested on an Android device or Android emulator with API 21
> Restore the rooms search of Element

- changelog.d/692.bugfix
- vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt
In case of forum, the button: "Remove this room from the forum directory" is not displayed. 
Regression due to the last rebase.
- Step 1
- Step 2
- Step ...
> Fix bug: remove this room from forum list is not displayed

- changelog.d/695.bugfix
- vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt
- vector/src/main/res/values-fr/strings_tchap.xml
- vector/src/main/res/values/strings.xml
#695 
The issue was caused to asynchronous changes inside the `withState` method, the CreateRoomParams object was returned before receiving the async changes
> Fix: "Forum creation: limited to my domain is not working"

- changelog.d/780.misc
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageAudioItem.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageVoiceItem.kt
- vector/src/main/res/layout/item_timeline_event_audio_stub.xml
- vector/src/main/res/layout/item_timeline_event_voice_stub.xml
Activate the antivirus for audio files and voice messages
Show an indicator in the timeline about the scan result like for the other media
Disable clicks if the media is infected
#780 
Trusted:
https://user-images.githubusercontent.com/11990514/206188940-c1b08d64-ed91-4296-a336-3a28581bff00.mp4
Infected (fake):
https://user-images.githubusercontent.com/11990514/206189000-ffd6a70f-a55a-4a4d-b4fc-94cb1ab1de60.mp4
- Send voice messages and mp3 files in a room
- Verify that the files are marked as not infected and can be played
- In the code, invert the condition in `MessageAudioItem.Holder` and `MessageVoiceItem.Holder`
- Test again and verify that the files are marked as infected, all the actions should be blocked
> Activate the content scanner for audio files

- changelog.d/776.bugfix
- vector/src/main/java/fr/gouv/tchap/features/roomprofile/settings/linkaccess/TchapRoomLinkAccessFragment.kt
> Fix crash on open the "access by link" screen

- changelog.d/945.improvements
- matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt
- matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/store/RustCryptoStore.kt
- vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
- vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt
> Supprimer le blocage d'envoi de messages chiffrés aux appareils non vérifiés

- changelog.d/950.fix
- vector-app/src/fdroid/java/im/vector/app/push/fcm/FdroidNotificationTroubleshootTestManagerFactory.kt
- vector-app/src/gplay/java/im/vector/app/push/fcm/GoogleNotificationTroubleshootTestManagerFactory.kt
Fix #950 
Suppression du test de disponibilité du serveur de Push notification basé sur le nom de serveur, non exposé au public dans le cas de Tchap.
> Remove Push Notification diagnostic test on server name

- changelog.d/953.bugfix
- vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSaveRecoveryKeyFragment.kt
Fix #953 
Accepter de fermer la pop-up de code de récupération même si le retour est "RESULT_CANCELED" car on ne peut pas facilement savoir si l'utilisateur a fait le nécessaire pour sauvegarder son code.
Le code est présent dans le clipboard à ce moment-là.
> Problème de copie du code de récupération après génération

- .github/workflows/build.yml
- changelog.d/959.misc
- vector-app/build.gradle
- vector/src/main/AndroidManifest.xml
#959 
remove calendar permissions according to https://github.com/vector-im/riot-android/pull/3106
> Remove calendar permissions

- changelog.d/979.bugfix
- matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/RustCryptoService.kt
> Fix crypto migration for mono session

- vector/src/main/java/im/vector/app/core/platform/VectorBaseActivity.kt
- vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt
Secure flag management improvement
- Step 1
- Step 2
- Step ...
> Update secure flag

- changelog.d/885.bugfix
- vector/src/main/java/fr/gouv/tchap/features/home/roomdirectory/createroom/TchapRoomAvatarWithNameItem.kt
The App crash in room creation screen after editing the room name.
related to #885 
- Go to room creation screen
- Focus on room name text input field
- Enter a room name
- Tap on done key
- Step 1
- Step 2
- Step ...
> Fix crash in room creation screen

- towncrier.toml
- vector-app/build.gradle
- vector/src/main/java/im/vector/app/features/settings/VectorSettingsActivity.kt
- vector/src/main/java/im/vector/app/features/settings/VectorSettingsRootFragment.kt
> Fix crash on happy holidays button

- changelog.d/1007.improvements
- library/ui-strings/src/main/res/values-fr/strings_tchap.xml
- library/ui-strings/src/main/res/values/strings_tchap.xml
- vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsAction.kt
- vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt
- vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsFragment.kt
- vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt
- vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewState.kt
#1007 
- Step 1
- Step 2
- Step ...
> Remove the option "Convertir en salon privé (irréversible)"

- changelog.d/1010.misc
- library/ui-strings/src/main/res/values-fr/strings_tchap.xml
- library/ui-strings/src/main/res/values/strings_tchap.xml
- vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/CallTileTimelineItem.kt
- vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
- vector/src/main/java/im/vector/app/features/rageshake/ReportType.kt
https://github.com/tchapgouv/tchap-product/issues/267
> Add VoIP bug report type

- changelog.d/1014.improvements
- library/ui-strings/src/main/res/values-fr/strings.xml
- library/ui-strings/src/main/res/values-fr/strings_tchap.xml
- library/ui-strings/src/main/res/values/strings.xml
- library/ui-strings/src/main/res/values/strings_tchap.xml
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptedItemFactory.kt
#1014 
- Step 1
- Step 2
- Step ...
> Harmonize UTD message

- changelog.d/1019.misc
- vector-app/src/androidTest/java/im/vector/app/ui/robot/NewRoomRobot.kt
- vector-app/src/androidTest/java/im/vector/app/ui/robot/OnboardingRobot.kt
- vector-app/src/androidTest/java/im/vector/app/ui/robot/space/SpaceRobot.kt
- vector-app/src/debug/java/im/vector/app/features/debug/di/FeaturesModule.kt
- vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
- vector-app/src/release/java/im/vector/app/core/di/FeaturesModule.kt
- vector-config/src/btchap/res/values/config-settings.xml
- vector-config/src/debug/res/values/config-settings.xml
- vector-config/src/devTchap/res/values/config-settings.xml
- vector-config/src/main/res/values/config-settings.xml
- vector-config/src/tchap/res/values/config-settings.xml
- vector/src/androidTest/java/im/vector/app/features/voice/VoiceRecorderProviderTests.kt
- vector/src/main/java/im/vector/app/features/VectorFeatures.kt
- vector/src/main/java/im/vector/app/features/settings/VectorSettingsRootFragment.kt
- vector/src/main/res/xml/vector_settings_root.xml
- vector/src/test/java/im/vector/app/test/fakes/FakeVectorFeatures.kt
Labs should be visible for developers and Tchap admin user
- Step 1
- Step 2
- Step ...
> Update labs visibility

- library/ui-strings/src/main/res/values-fr/strings.xml
#1017 
- Step 1
- Step 2
- Step ...
> Update deactivate account strings

- changelog.d/642.bugfix
- changelog.d/766.bugfix
- changelog.d/851.bugfix
- changelog.d/911.bugfix
- library/multipicker/src/main/java/im/vector/lib/multipicker/AudioPicker.kt
- library/multipicker/src/main/java/im/vector/lib/multipicker/CameraPicker.kt
- library/multipicker/src/main/java/im/vector/lib/multipicker/ContactPicker.kt
- library/multipicker/src/main/java/im/vector/lib/multipicker/FilePicker.kt
- library/multipicker/src/main/java/im/vector/lib/multipicker/ImagePicker.kt
- library/multipicker/src/main/java/im/vector/lib/multipicker/MediaPicker.kt
- library/multipicker/src/main/java/im/vector/lib/multipicker/Picker.kt
- library/multipicker/src/main/java/im/vector/lib/multipicker/VideoPicker.kt
- matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailAction.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewEvents.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/EventSharedAction.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
Fix #642 #766 #851 #911
- Step 1
- Step 2
- Step ...
> Fix file access permission

- changelog.d/1037.improvements
- library/ui-strings/src/main/res/values-fr/strings_tchap.xml
- library/ui-strings/src/main/res/values/strings_tchap.xml
- vector/src/main/java/im/vector/app/features/settings/notifications/VectorSettingsNotificationFragment.kt
#1037 
- Step 1
- Step 2
- Step ...
> Add notification email description

- changelog.d/1049.bugfix
- vector-config/src/tchap/res/values/config-features.xml
- vector/src/withpinning/res/xml/network_security_config.xml
Limit VoIP for DINUM agents
- Step 1
- Step 2
- Step ...
> Add security exception for openmaptiles.github.io

- TCHAP_CHANGES.md
- changelog.d/1049.bugfix
- towncrier.toml
- vector-app/build.gradle
- vector/src/withpinning/res/xml/network_security_config.xml
> Revert security exception

- changelog.d/1057.misc
- library/ui-strings/src/main/res/values-fr/strings.xml
- towncrier.toml
- vector-app/build.gradle
|Before|After|
|-|-|
|<img src="https://github.com/tchapgouv/tchap-android/assets/1191674/be92c3ad-4ab2-4a54-af64-0b4f5eaab3ff" width="500" />|<img src="https://github.com/tchapgouv/tchap-android/assets/1191674/05ef80e1-934b-435e-9600-27d795190973" width="500" />|
- Step 1
- Step 2
- Step ...
> Update warning location wording

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/nightly.yml
- .github/workflows/post-pr.yml
- .github/workflows/quality.yml
- .github/workflows/tests.yml
- changelog.d/1055.improvements
- dependencies.gradle
- dependencies_groups.gradle
- library/attachment-viewer/build.gradle
- library/core-utils/build.gradle
- library/external/autocomplete/build.gradle
- library/external/dialpad/build.gradle
- library/external/jsonviewer/build.gradle
- library/multipicker/build.gradle
- library/ui-strings/build.gradle
- library/ui-styles/build.gradle
- matrix-sdk-android-flow/build.gradle
- matrix-sdk-android/build.gradle
- vector-app/build.gradle
- vector-config/build.gradle
- vector/build.gradle
- vector/src/withdmvoip/java/im/vector/app/features/call/webrtc/WebRtcCallManager.kt
> Set webrtc proxy

- changelog.d/988.feature
- library/ui-strings/src/main/res/values-fr/strings.xml
- vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
- vector-config/src/btchap/res/values/config-features.xml
- vector-config/src/devTchap/res/values/config-features.xml
- vector-config/src/tchap/res/values/config-features.xml
- vector/src/main/java/im/vector/app/features/VectorFeatures.kt
- vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModel.kt
- vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSetupRecoveryKeyFragment.kt
- vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSharedViewModel.kt
- vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationController.kt
- vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationViewModel.kt
- vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
- vector/src/main/java/im/vector/app/features/raw/wellknown/ElementWellKnown.kt
Secure backup is required
#988 
|aucun appareil - pas de sauvegarde|autre(s) appareil(s) - pas de sauvegarde|autre(s) appareil(s) - sauvegarde existante|aucun appareil - sauvegarde existante|
|-|-|-|-|
|![image](https://github.com/tchapgouv/tchap-android/assets/1191674/675114cf-526e-4b95-8b78-179d57fbfaa4)|![image](https://github.com/tchapgouv/tchap-android/assets/1191674/4af63f8e-70ac-43a5-be8c-0a5f1731668b)|![image](https://github.com/tchapgouv/tchap-android/assets/1191674/4ad4e5e1-2416-41cd-b452-96d3774b3674)|![image](https://github.com/tchapgouv/tchap-android/assets/1191674/907dc8a8-27b8-43ee-a4a3-50f2834cbed6)|
|![image](https://github.com/tchapgouv/tchap-android/assets/1191674/1815431b-6c0d-44c3-8400-b705124b895a)|![image](https://github.com/tchapgouv/tchap-android/assets/1191674/2b6 …
> Secure backup is required

- changelog.d/1078.feature
- towncrier.toml
- vector-app/build.gradle
- vector-app/src/debug/java/im/vector/app/features/debug/features/DebugVectorFeatures.kt
- vector-config/src/btchap/res/values/config-features.xml
- vector-config/src/devTchap/res/values/config-features.xml
- vector-config/src/main/res/values/config-settings.xml
- vector-config/src/tchap/res/values/config-features.xml
- vector-config/src/withdmvoip/res/values/config-features.xml
- vector-config/src/withvoip/res/values/config-features.xml
- vector/src/main/java/im/vector/app/features/VectorFeatures.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/CallItemFactory.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/WidgetItemFactory.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/CallTileTimelineItem.kt
- vector/src/main/res/xml/vector_settings_root.xml
#1078 
- Step 1
- Step 2
- Step ...
> Enable visio for DINUM instance

- changelog.d/1080.bugfix
- matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/timeline/decorator/UpdatedReplyDecorator.kt
- matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/sync/handler/room/ThreadsAwarenessHandler.kt
> Display reply to only if the root event is a text message.

- changelog.d/1082.bugfix
- library/ui-strings/src/main/res/values-fr/strings.xml
- matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/FileUploader.kt
- vector/src/main/java/im/vector/app/features/home/AvatarRenderer.kt
- vector/src/main/java/im/vector/app/features/html/PillImageSpan.kt
#1082
- Step 1
- Step 2
- Step ...
> Fix avatar size in pill

- vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt
#1086
- Step 1
- Step 2
- Step ...
> Hide visio item

- vector-app/proguard-rules.pro
- vector/build.gradle
Release can't build
- Step 1
- Step 2
- Step ...
> Update R8 (proguard) configuration to support guava

- changelog.d/1083.improvements
- towncrier.toml
- vector-app/build.gradle
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/EventSharedAction.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
- vector/src/main/res/drawable/ic_report_custom.xml
#1083 
|Before|After|
|-|-|
|<img width="503" alt="image" src="https://github.com/user-attachments/assets/96fc4b6a-c555-48ea-9613-6d140ad7d8cc">|<img width="503" alt="image" src="https://github.com/user-attachments/assets/1eb0577c-7466-4140-a1de-63992690f54c">|
- Step 1
- Step 2
- Step ...
> Improve content report

- changelog.d/1101.bugfix
- vector-config/src/main/java/im/vector/app/config/Config.kt
- vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
- vector/src/main/java/im/vector/app/features/home/HomeActivityViewEvents.kt
- vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
- vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt
- vector/src/withdmvoip/java/im/vector/app/features/call/webrtc/WebRtcCall.kt
- vector/src/withdmvoip/java/im/vector/app/features/call/webrtc/WebRtcCallManager.kt
Enable analytics on debug and fix call duration when event is tracked
- Step 1
- Step 2
- Step ...
> Enable analytics on debug

- changelog.d/1106.feature
- changelog.d/1108.bugfix
- towncrier.toml
- vector-app/build.gradle
- vector-config/src/tchap/res/values/config-features.xml
- vector/src/main/AndroidManifest.xml
- vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
> Enable visio on education instance

- changelog.d/1118.improvements
- vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt
#1118 
- Step 1
- Step 2
- Step ...
> Add explicit error when a user is not allowed to access a room.

- changelog.d/1113.improvements
- changelog.d/1116.improvements
- library/ui-strings/src/main/res/values-fr/strings.xml
- library/ui-strings/src/main/res/values-fr/strings_tchap.xml
- library/ui-strings/src/main/res/values/strings.xml
- library/ui-strings/src/main/res/values/strings_tchap.xml
- vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationController.kt
- vector/src/main/java/im/vector/app/features/crypto/verification/self/SelfVerificationFragment.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/EncryptedItemFactory.kt
#1116 
#1113 
- Step 1
- Step 2
- Step ...
> Add help item in bottom sheet verification

- changelog.d/1120.feature
- changelog.d/1121.feature
- vector-config/src/tchap/res/values/config-features.xml
#1120 
- Step 1
- Step 2
- Step ...
> Enable visio for Intradef instance

- changelog.d/1126.bugfix
- vector/src/main/java/im/vector/app/core/services/CallAndroidService.kt
#1126 
- Step 1
- Step 2
- Step ...
> Fix crash for incoming call

- changelog.d/1112.improvements
- library/ui-strings/src/main/res/values-fr/strings_tchap.xml
- library/ui-strings/src/main/res/values/strings_tchap.xml
> Update access by link wording

- changelog.d/1136.feature
- towncrier.toml
- vector-app/build.gradle
- vector-config/src/tchap/res/values/config-features.xml
#1136 
- Step 1
- Step 2
- Step ...
> Enable visio for all instances

- README.md
Add the app certificate fingerprint to the README file, enabling apps and users to check the integrity of apk installed from github.
The main purpose is to enable subsequent verification of the app through [AppVerifier](https://github.com/soupslurpr/AppVerifier), including adding the fingerprint to its internal database.
> Added SHA1 & SHA256 application certificate fingerprints to README

- README.md
- changelog.d/1143.misc
- vector-config/src/main/java/im/vector/app/config/Config.kt
- vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
- vector/src/main/java/im/vector/app/features/settings/VectorSettingsUrls.kt
- vector/src/main/java/im/vector/app/features/settings/legals/ElementLegals.kt
- vector/src/main/java/im/vector/app/features/settings/legals/LegalsFragment.kt
> Update TAC and private policy URLs

- changelog.d/1152.sdk
- matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultFileService.kt
- matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/DefaultContentUrlResolver.kt
- matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/contentscanner/DefaultContentScannerService.kt
- vector/src/main/java/im/vector/app/features/home/AvatarRenderer.kt
#1153 
- Step 1
- Step 2
- Step ...
> Support authenticated media with content scanner

- changelog.d/1155.bugfix
- dependencies.gradle
https://github.com/element-hq/element-android/issues/9010
- Step 1
- Step 2
- Step ...
> Restore rich text editor version 2.37.6

- changelog.d/1162.feature
- library/ui-strings/src/main/res/values-fr/strings_tchap.xml
- library/ui-strings/src/main/res/values/strings_tchap.xml
- vector/src/main/java/im/vector/app/features/command/Command.kt
- vector/src/main/java/im/vector/app/features/command/CommandParser.kt
- vector/src/main/java/im/vector/app/features/command/ParsedCommand.kt
- vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
Ajout d'une commande /visio pour créer un lien vers La Suite Visio
- Step 1
- Step 2
- Step ...
> Add visio command
