tchapgouv/tchap-android

vector/src/main/AndroidManifest.xml, vector/src/main/java/fr/gouv/tchap/features/login/TchapFirstLoginFragment.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginAction.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginActivity.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginViewEvents.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginViewModel.kt
- Remove some code related to the homeserver selection
- Remove some code related to the fallback on weblogin
- Comment intent filter in Manifest (SSO login is not supported)
These points are irrelevant in Tchap now and in the near future
=> Code cleaning

vector/src/main/java/fr/gouv/tchap/features/login/TchapAbstractLoginFragment.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginAction.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginActivity.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginViewModel.kt, vector/src/main/java/im/vector/app/core/dialogs/UnrecognizedCertificateDialog.kt, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Code cleaning2

vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginActivity.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginFragment.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginViewModel.kt, vector/src/main/java/fr/gouv/tchap/features/login/registration/TchapRegisterFragment.kt, vector/src/main/java/im/vector/app/core/di/FragmentModule.kt, vector/src/main/res/layout/fragment_tchap_register.xml
=> Add register screen and get Tchap platform configuration

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/registration/RegistrationWizard.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/MatrixError.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/AddThreePidRegistrationParams.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/DefaultRegistrationWizard.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/registration/RegisterAddThreePidTask.kt, vector/src/main/java/fr/gouv/tchap/core/utils/TchapUtils.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapAbstractLoginFragment.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginAction.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginActivity.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginFragment.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginViewEvents.kt, vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginViewModel.kt, vector/src/main/java/fr/gouv/tchap/features/login/registration/TchapRegisterFragment.kt, vector/src/main/java/fr/gouv/tchap/features/login/registration/TchapRegisterWaitForEmailFragment.kt, vector/src/main/java/im/vector/app/core/di/FragmentModule.kt, vector/src/main/res/layout/fragment_tchap_register_wait_for_email.xml
=> Set up the account creation

vector/src/main/java/fr/gouv/tchap/features/login/TchapLoginFragment.kt
=> Sign in process: the potential errors are not displayed

vector/src/main/AndroidManifest.xml, vector/src/main/res/layout/fragment_home_detail.xml, vector/src/main/res/layout/fragment_tchap_register_wait_for_email.xml, vector/src/main/res/values/colors.xml, vector/src/main/res/values/colors_tchap.xml, vector/src/main/res/values/styles_riot.xml, vector/src/main/res/values/styles_tchap.xml, vector/src/main/res/values/theme_tchap_variant1_light.xml, vector/src/main/res/values/theme_tchap_variant2_light.xml, vector/src/preprod/res/values/config.xml
=> Set up Tchap color and light theme

matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/session/events/model/TchapEventType.kt, matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/session/room/model/RoomAccessRules.kt, matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/session/room/model/RoomAccessRulesContent.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomSummary.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/RealmSessionStoreMigration.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/mapper/RoomSummaryMapper.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/database/model/RoomSummaryEntity.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/summary/RoomSummaryUpdater.kt, vector/src/main/java/fr/gouv/tchap/core/utils/RoomUtils.kt, vector/src/main/java/fr/gouv/tchap/features/home/room/list/TchapRoomSummaryItem.kt
=> Support the room access rules state event

vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListController.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewModel.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewState.kt
=> Resolve matrixId to get Tchap user

TCHAP_CHANGES.md, vector/src/main/java/im/vector/app/core/resources/BooleanProvider.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/actions/RoomListQuickActionsEpoxyController.kt, vector/src/main/java/im/vector/app/features/home/room/list/actions/RoomListQuickActionsSharedAction.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Simplify the notifications modes

TCHAP_CHANGES.md, vector/src/main/java/fr/gouv/tchap/features/home/room/list/TchapRoomSummaryItemFactory.kt, vector/src/main/res/layout/item_tchap_room_invitation.xml, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings_tchap.xml
=> Change the invite description

TCHAP_CHANGES.md, matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/internal/session/room/TchapRoomGetter.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomGetter.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/RoomModule.kt
=> Be able to select the best direct chat related to a user id 

TCHAP_CHANGES.md, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/GroupRoomListSectionBuilder.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListAction.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/SpaceRoomListSectionBuilder.kt
=> [Home screen] cancel the search when the user selects an item from the search result

vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListAction.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListFragment.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewModel.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
=> Contacts list: Handle contacts access permission

vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListController.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListFragment.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListFragmentArgs.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewEvents.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewModel.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewState.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/res/drawable/ic_tchap_contact_search.xml, vector/src/main/res/layout/fragment_home_detail.xml, vector/src/main/res/layout/item_contact_action.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> [Contacts list] Add the option to search in the users directory

vector/src/main/java/im/vector/app/features/home/HomeDetailAction.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailViewEvents.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings_tchap.xml
=> [Invite by Email] open the DM (if any) when an existing user is discovered

vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListFragment.kt
=> [Contact list] Fix contact permission

vector/src/main/res/layout/fragment_room_preview_no_preview.xml
=> [Public rooms] - Forum preview

vector/src/main/java/fr/gouv/tchap/core/utils/TchapUtils.kt, vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomItem.kt, vector/src/main/java/im/vector/app/features/roomdirectory/PublicRoomsController.kt, vector/src/main/res/layout/item_public_room.xml
=> [Public rooms] Apply Tchap design on the forum cells

vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListController.kt, vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewModel.kt, vector/src/main/java/fr/gouv/tchap/features/home/room/list/TchapRoomSummaryItemFactory.kt, vector/src/main/java/im/vector/app/features/userdirectory/UserDirectoryUserItem.kt
=> [Contacts list] Remove the potential deactivated users from the contacts list

vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt, vector/src/main/res/layout/view_attachment_type_selector.xml, vector/src/main/res/menu/menu_timeline.xml, vector/src/main/res/xml/vector_settings_general.xml
=> Hide the integration manager references

vector/src/main/java/im/vector/app/features/home/HomeDetailAction.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailViewEvents.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings_tchap.xml
=> Prompt the user to create a DM when he selects a contact without DM yet

TCHAP_CHANGES.md, matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/api/session/room/model/RoomAccessRulesContent.kt, vector/src/main/java/fr/gouv/tchap/core/utils/RoomUtils.kt, vector/src/main/java/fr/gouv/tchap/core/utils/TchapUtils.kt, vector/src/main/java/fr/gouv/tchap/features/home/roomdirectory/createroom/TchapCreateRoomController.kt, vector/src/main/java/fr/gouv/tchap/features/home/roomdirectory/createroom/TchapRoomTypeForumItem.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomAction.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomFragment.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt
=> Set up the new room creation screen (Implementation) 

vector/src/main/java/fr/gouv/tchap/features/home/contact/list/TchapContactListViewModel.kt
=> Handle uncaught exceptions

vector/build.gradle, vector/src/main/java/im/vector/app/features/crypto/verification/epoxy/BottomSheetSelfWaitItem.kt, vector/src/main/java/im/vector/app/features/crypto/verification/request/VerificationRequestController.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt, vector/src/main/java/im/vector/app/features/workers/signout/ServerBackupStatusViewModel.kt, vector/src/main/java/im/vector/app/features/workers/signout/SignOutBottomSheetDialogFragment.kt, vector/src/main/java/im/vector/app/features/workers/signout/SignoutCheckViewModel.kt, vector/src/main/res/layout/item_verification_wait.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings.xml, vector/src/main/res/values/strings_tchap.xml
=>  Hide the key backup service of the secured storage

vector/src/main/java/im/vector/app/features/home/HomeDetailViewModel.kt
=> [Invite by email] Resolve user by matrix id

matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/internal/session/room/TchapRoomGetter.kt
=> Crash on session verification with emojis

vector/build.gradle, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsSecurityPrivacyFragment.kt, vector/src/main/res/xml/vector_settings_security_privacy.xml
=> Make optional the cross-signing feature

TCHAP_CHANGES.md, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/helper/TimelineDisplayableEvents.kt
=> Adjust the design in the room details screen

vector/src/main/java/fr/gouv/tchap/features/home/room/list/TchapRoomSummaryItem.kt, vector/src/main/java/fr/gouv/tchap/features/home/room/list/TchapRoomSummaryItemFactory.kt
=> Some group room are displayed with a rounded avatar

vector/src/main/java/fr/gouv/tchap/features/home/roomdirectory/createroom/TchapRoomTypeExternalItem.kt, vector/src/main/java/fr/gouv/tchap/features/home/roomdirectory/createroom/TchapRoomTypeForumItem.kt, vector/src/main/java/fr/gouv/tchap/features/home/roomdirectory/createroom/TchapRoomTypePrivateItem.kt, vector/src/main/res/values/layout.xml
=> Add room type layout aliases

vector/src/main/java/fr/gouv/tchap/core/utils/RoomUtils.kt, vector/src/main/java/fr/gouv/tchap/features/home/roomdirectory/createroom/TchapCreateRoomController.kt, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailViewModel.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt
=> [Room creation] The forum option is not working android

vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
=>  Hide the room parameters and members in case of a direct chat

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/RoomHistoryVisibility.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsAction.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsFragment.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewState.kt
=> [Room Settings] Let the admin convert a forum in a private room 

vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt
=> Hide room alias setting

library/ui-styles/src/main/res/values/palette.xml, library/ui-styles/src/main/res/values/palette_mobile.xml
=> Configure the Dark/Black modes

vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomAction.kt, vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt, vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomByQrCodeFragment.kt, vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomViewModel.kt, vector/src/main/java/im/vector/app/features/userdirectory/PendingSelection.kt
=> Update the screen displayed to create a DM from the floating button menu

vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt
=> Clean forum settings

vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> [Direct Message] Update search placeholder

vector/src/main/java/im/vector/app/features/autocomplete/command/AutocompleteCommandPresenter.kt, vector/src/main/java/im/vector/app/features/command/Command.kt, vector/src/main/java/im/vector/app/features/command/CommandParser.kt
=> Block some slash command

vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/res/xml/vector_settings_preferences.xml
=> [Settings] Adjust Preferences

vector/build.gradle, vector/src/main/res/xml/vector_settings_root.xml
=>  [Settings] hide "Voice & Video" section when the voip is not available

TCHAP_CHANGES.md, vector/src/main/java/im/vector/app/features/disclaimer/DisclaimerDialog.kt, vector/src/main/res/layout/dialog_disclaimer_content.xml, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values/strings.xml
=> Update migration dialog

TCHAP_CHANGES.md, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivitySharedAction.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListAction.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListFragment.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewEvents.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomListViewModel.kt
=> Fix application tabs are not updated correctly

TCHAP_CHANGES.md, vector/src/main/res/xml/vector_settings_help_about.xml
=> [Settings] adjust Help & About section

TCHAP_CHANGES.md, changelog.d/306.improvements, vector/build.gradle, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/MessageFileItem.kt
=> Wrong icon displayed for an infected file

TCHAP_CHANGES.md, vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsViewModel.kt
=> [Room settings] Actions must be disabled on infected attachment in the attachments list #304

vector/src/main/java/im/vector/app/features/roomprofile/uploads/RoomUploadsViewModel.kt
=> [Room settings] Actions must be disabled on infected attachment in the attachments list

changelog.d/321.bugfix, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/settings/VectorSettingsHelpAboutFragment.kt
=> Fix term and conditions handled as a malformed permalink

changelog.d/323.improvements, vector/build.gradle, vector/src/main/java/im/vector/app/features/home/room/detail/RoomDetailFragment.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/TextComposerViewState.kt
=> Hide the voice message option

changelog.d/313.improvements, vector/src/main/java/im/vector/app/features/disclaimer/DisclaimerDialog.kt, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewActions.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
=> [Migration] Automatically give user consent to identity server policy

changelog.d/234.improvements, vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings_tchap.xml
=> [Account Creation] Translate in French the weak password errors

changelog.d/337.feature, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsAction.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsFragment.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewModel.kt, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsViewState.kt
#337 
Also fix created rooms not federated by default
=> Add setting to open the private room to the external users

changelog.d/340.improvements, vector/src/main/java/im/vector/app/features/roomprofile/settings/RoomSettingsController.kt
=> [Room Settings] Remove the "guest_access" option available in developer mode 

changelog.d/352.improvements, vector/src/main/java/im/vector/app/features/settings/BackgroundSyncMode.kt, vector/src/main/java/im/vector/app/features/settings/notifications/VectorSettingsNotificationPreferenceFragment.kt
=> Adjust F-Droid parameters

changelog.d/348.bugfix, vector/src/main/java/im/vector/app/features/crypto/verification/conclusion/VerificationConclusionController.kt, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings_tchap.xml
=> Unexpected white area in the verification bottom sheet

changelog.d/346.bugfix, vector/src/main/java/im/vector/app/features/themes/ActivityOtherThemes.kt, vector/src/main/res/layout/activity_main.xml
=> Wrong landing page on logout

changelog.d/345.improvements, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewState.kt, vector/src/main/res/values-fr/strings.xml, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings_tchap.xml
=> Prompt the last admin before letting them leave a room

changelog.d/373.improvements, vector/build.gradle, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
=> Add a flag to disable message edition

changelog.d/384.improvements, vector/src/main/res/xml/vector_settings_security_privacy.xml
=> Remove the optional screenshot from Security&Privacy

changelog.d/380.improvements, vector/build.gradle, vector/src/main/res/xml/vector_settings_root.xml
=> Hide Labs menu item in Tchap 

changelog.d/322.improvements, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/failure/Extensions.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/network/Request.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorCoroutine.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/send/queue/EventSenderProcessorThread.kt, vector/src/main/java/im/vector/app/core/error/ErrorFormatter.kt
Cherry-pick changes from https://github.com/vector-im/element-android/pull/4995 and fixes #322
=> [Login] Handle correctly M_LIMIT_EXCEEDED error code

vector/build.gradle
=> The apk generated on new tag have the unexpected prefix "-dev"

tools/release/sign_all_apks.sh
=> Improve the sign apk script

changelog.d/401.bugfix, matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/internal/session/room/TchapRoomGetter.kt
=> [Workaround] Do not select a DM left by the other user

changelog.d/392.bugfix, vector/src/main/java/im/vector/app/features/contactsbook/ContactsBookViewModel.kt, vector/src/main/java/im/vector/app/features/userdirectory/UserListViewModel.kt
=> [Invitation by email] Handle correctly Id server consent

changelog.d/410.improvements, vector/src/main/res/values-fr/strings_tchap.xml, vector/src/main/res/values/strings_tchap.xml
=> Change string "Tchap ne supporte pas encore les appels" to "Tchap ne supporte pas les appels"

changelog.d/412.improvements, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/format/DisplayableEventFormatter.kt
#412 
Note: The color has not been changed for now, it requires more changes related to the theming.
=> [Room list] Remove bold for the sender in the last message preview

changelog.d/437.misc, vector/src/agent/res/values/config.xml, vector/src/preprod/res/values/config.xml
=> Change sygnal server url

changelog.d/440.bugfix, vector/src/main/res/layout/item_login_header.xml
=> Update the application logo in the soft logout screen

changelog.d/453.bugfix, vector/src/main/res/layout/fragment_home_drawer.xml
=> hide logout button in left menu

changelog.d/393.bugfix, vector/src/main/java/im/vector/app/features/createdirect/CreateDirectRoomActivity.kt, vector/src/main/java/im/vector/app/features/home/HomeDetailFragment.kt
=> [Invite by Email] Toast is not displayed correctly

.github/workflows/quality.yml, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt
=> fix Quality.yml

changelog.d/471.misc, vector/src/main/AndroidManifest.xml
=> Disable Android Auto support

changelog.d/465.improvements, vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItem.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItemFactory.kt, vector/src/main/res/drawable/ic_tchap_pin_room.xml, vector/src/main/res/layout/item_tchap_room.xml
=> [Rooms list] Remove the pinned room marker

changelog.d/494.misc, vector/src/main/java/im/vector/app/features/settings/VectorPreferences.kt, vector/src/main/res/xml/vector_settings_preferences.xml
=> Turn on by default the Markdown and the Bubbles

changelog.d/512.bugfix, vector/src/main/res/xml/vector_settings_advanced_settings.xml
=> hide "Dev Tools" if developer mode is hidden

changelog.d/517.bugfix, vector/src/withoutpinning/res/xml/network_security_config.xml
=> Fix SSL errors on some devices using fdroid version

changelog.d/510.misc, library/ui-styles/src/main/res/values/colors_message_bubble.xml, library/ui-styles/src/main/res/values/palette.xml, library/ui-styles/src/main/res/values/palette_mobile.xml
=> Update the bubble background color

AUTHORS.md, CONTRIBUTING.md, README.md
- updated the Tchap readme
- updated the Tchap authors
- minor cleanup in contributing file
=> Update markdown files

changelog.d/521.bugfix, vector/build.gradle
=> [Release] The application name is Element

changelog.d/520.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt, vector/src/main/res/layout/view_attachment_type_selector.xml
=> Hide sticker button 

changelog.d/548.bugfix, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
=> Hide edit message option

TCHAP_CHANGES.md, changelog.d/548.bugfix, towncrier.toml, vector/build.gradle, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
This version disables the edition of the messages
=> Hotfix/tchap v2.2.1

changelog.d/398.bugfix, vector/src/main/res/layout/item_timeline_event_file_stub.xml
=> [Infected file] file description cropped

changelog.d/592.misc, vector/build.gradle
=> Enable editing and reaction

changelog.d/599.bugfix, vector-config/src/main/res/values/config-features.xml, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsViewModel.kt
=> Remove "answer in a thread" from the message's quick actions

changelog.d/458.improvments, vector/build.gradle, vector/src/main/java/im/vector/app/features/crypto/recover/BootstrapSetupRecoveryKeyFragment.kt, vector/src/main/res/layout/fragment_bootstrap_setup_recovery.xml
Enable cross-singning in dev and preprod
Enable keyback-up in dev and disable passphrase security
=> Enable cross-signing in preprod and dev and keyback up in dev

changelog.d/597.bugfix, vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
#597 
For preprod: use devTchap
For dev: btchap
For prod: tchap
=> Rageshake: Change Element to Tchap

.github/dependabot.yml, changelog.d/648.misc
Remove the dependabot GH action, Tchap get the lib updates on each Element rebase
=> Skip dependabot GH action

.github/workflows/post-pr.yml
=> Fix post-pr CI

changelog.d/661.bugfix, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt
=> Fix, encryption enabled on new forum

.github/dependabot.yml
=> try to disable dependabot

vector/src/main/java/im/vector/app/features/settings/VectorSettingsUrls.kt
Change url to more permanent url
We should use more permanent url
=> Fix FAQ url

.github/workflows/build.yml
Add new target to automatically build
I need dev APKs for testing purpose.
I want to test VoIP to
=> Add New Targets to build

changelog.d/668.improvments, vector/src/main/res/layout/item_tchap_room_invitation.xml
=> Using a secondary button style in the case of binary actions

changelog.d/674.bugfix, vector/src/main/java/im/vector/app/features/crypto/verification/conclusion/VerificationConclusionController.kt, vector/src/main/java/im/vector/app/features/crypto/verification/epoxy/BottomSheetVerificationBigImageItem.kt
=> ISSUE-674: Display shields at the end of verification

changelog.d/686.misc, vector/src/main/java/im/vector/app/features/home/HomeActivity.kt
=> [Menu - Report Bug] Disable by default Send Screenshot

changelog.d/687.misc, vector/src/main/res/layout/item_tchap_editable_avatar_with_name.xml
=> Enable auto-capitalization for Room creation Title field

.github/workflows/quality.yml
Using a token from a Github Apps instead of a PAT
=> fix-danger-bot-token

.github/workflows/quality.yml, changelog.d/714.misc, tools/danger/dangerfile.js, vector/build.gradle, vector/src/main/java/im/vector/app/features/home/HomeDrawerFragment.kt
Following #714, this PR updates the configuration of Danger for Tchap
=> Configure Danger

vector/src/main/java/im/vector/app/features/home/room/list/RoomListSectionBuilder.kt
bypass temporarily live suggested rooms to prevent infinite load on empty room list
- OS version(s): Android 13
=> bypass temporarily live suggested rooms to prevent infinite load

changelog.d/784.misc, vector-config/src/main/res/values/config-settings.xml
Disable the app layout by default (keep the previous layout)
The new app layout is enabled by default in Element-1.5.2. We'll disable it for the moment in Tchap because the spaces are not supported.
=> Disable app layout by default

library/ui-strings/src/main/res/values-fr/strings.xml, library/ui-strings/src/main/res/values/strings.xml, vector/src/main/res/layout/fragment_ftue_reset_password_input.xml
https://github.com/tchapgouv/tchap-design/issues/97
- Open a disconnect app
- Go to login -> reset password
- Enter an email
- Enter ok
- The checkbox should be unchecked
=> Set reset password disconnect checkbox default to false

changelog.d/857.bugfix, vector/src/main/java/im/vector/app/features/workers/signout/SignOutBottomSheetDialogFragment.kt, vector/src/main/java/im/vector/app/features/workers/signout/SignoutCheckViewModel.kt
=> Fix crash on logout

changelog.d/853.bugfix, vector-app/build.gradle, vector/build.gradle
=> Prevent selecting multiple languages

library/ui-strings/src/main/res/values-fr/strings.xml
=> Update strings fr

.github/workflows/build.yml, coverage.gradle, library/ui-strings/src/main/res/values-fr/strings.xml, vector-app/build.gradle, vector/src/main/java/im/vector/app/features/command/Command.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/composer/MessageComposerViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/list/RoomSummaryItemFactory.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt, vector/src/test/java/im/vector/app/features/command/CommandParserTest.kt
=> Fix conflicts on Rebase/element android 1.5.26

changelog.d/856.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomBodyBuilder.kt
Fix https://github.com/tchapgouv/tchap-android/issues/856
=> Fix Error 500 when inviting external email in a DM

changelog.d/949.bugfix, changelog.d/965.bugfix, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomBodyBuilder.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt
=> Fix bad identity url

changelog.d/955.improvements, library/ui-strings/src/main/res/values-fr/strings.xml, library/ui-strings/src/main/res/values-fr/strings_tchap.xml, library/ui-strings/src/main/res/values/strings.xml, library/ui-strings/src/main/res/values/strings_tchap.xml, vector/src/main/java/im/vector/app/features/sync/widget/SyncStateView.kt
=> Add service status url

changelog.d/964.bugfix, vector/src/main/java/im/vector/app/features/home/ShortcutsHandler.kt
=> Fix crash on new shortcuts

matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/internal/auth/AccountValidityAPI.kt
=> Update account_validity requests

changelog.d/971.feature, vector/src/main/res/xml/vector_settings_notifications.xml
#971 
- Step 1
- Step 2
- Step ...
=> Add email notifications setting

changelog.d/976.improvements, library/attachment-viewer/build.gradle, library/ui-styles/build.gradle, towncrier.toml, vector-app/build.gradle, vector-config/build.gradle, vector/build.gradle
Remove jitsi meet dependency
- Step 1
- Step 2
- Step ...
=> Manage jitsi libs

matrix-sdk-android/src/kotlinCrypto/java/org/matrix/android/sdk/internal/crypto/store/db/RealmCryptoStore.kt, matrix-sdk-android/src/rustCrypto/java/org/matrix/android/sdk/internal/crypto/store/RustCryptoStore.kt, vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineViewModel.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileAction.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileController.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileFragment.kt, vector/src/main/java/im/vector/app/features/roomprofile/RoomProfileViewModel.kt
=> Force to false to deactivate "Never send messages to unverified devices"

changelog.d/975.improvements, vector/src/main/java/im/vector/app/features/command/Command.kt
Add some slash commands
- Step 1
- Step 2
- Step ...
=> Update command list

towncrier.toml, vector-app/build.gradle
=> Upgrade version number

changelog.d/982.bugfix, matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/api/auth/login/TchapLoginWizard.kt, matrix-sdk-android/src/main/java/fr/gouv/tchap/android/sdk/internal/session/room/TchapRoomGetter.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/login/DefaultLoginWizard.kt, vector/src/main/java/im/vector/app/core/extensions/BasicExtensions.kt
Update email validation in accordance with RFC 5322
- Step 1
- Step 2
- Step ...
=> Fix email address pattern

changelog.d/991.improvements, vector-config/src/devTchap/res/values/config.xml
https://github.com/tchapgouv/tchap-web-v4/issues/821
- Step 1
- Step 2
- Step ...
=> Update dev endpoints

changelog.d/995.bugfix, library/ui-strings/src/main/res/values-fr/strings_tchap.xml, library/ui-strings/src/main/res/values/strings_tchap.xml, vector/src/main/java/im/vector/app/features/home/room/detail/TimelineFragment.kt
Afficher une dialogue pour bloquer l'installation d'une application android
L'application crash quand on essaie d'ouvrir un APK : #995 
- Step 1
- Step 2
- Step ...
- [] Pull request updates [TCHAP_CHANGES.md](https://github.com/tchapgouv/tchap-android-v2/blob/develop/TCHAP_CHANGES.md)
=> Block apk install

changelog.d/948.improvements, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt
#948 
- Step 1
- Step 2
- Step ...
=> Improve on-screen keyboard interaction when logging in

changelog.d/999.improvements, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewModel.kt, vector/src/main/java/im/vector/app/features/roomdirectory/createroom/CreateRoomViewState.kt
#999 
- Step 1
- Step 2
- Step ...
=> Disable domain limit

.github/workflows/build.yml, .github/workflows/quality.yml, .github/workflows/sanity_test.yml, .github/workflows/tests.yml, CONTRIBUTING.md, coverage.gradle, docs/ui-tests.md, towncrier.toml, vector-app/build.gradle, vector-config/src/tchap/res/values/config-features.xml
=> Re-activate VoIP

changelog.d/1020.feature, library/ui-strings/src/main/res/values/donottranslate.xml, vector-config/src/main/java/im/vector/app/config/Config.kt, vector/src/main/java/im/vector/app/core/epoxy/bottomsheet/BottomSheetMessagePreviewItem.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/LocationUiData.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/action/MessageActionsEpoxyController.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/LiveLocationShareMessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/factory/MessageItemFactory.kt, vector/src/main/java/im/vector/app/features/home/room/detail/timeline/item/AbsMessageLocationItem.kt, vector/src/main/java/im/vector/app/features/location/Config.kt, vector/src/main/java/im/vector/app/features/location/MapRenderer.kt, vector/src/main/java/im/vector/app/features/location/TchapMapRenderer.kt, vector/src/main/java/im/vector/app/features/location/UrlMapProvider.kt, vector/src/main/res/layout/item_tchap_room.xml
=> Enable location sharing

changelog.d/1021.bugfix, vector/src/withdmvoip/AndroidManifest.xml
Fix #1021 
- Step 1
- Step 2
- Step ...
=> Fix screen sharing

changelog.d/1035.improvements, library/ui-strings/src/main/res/values-fr/strings_tchap.xml, library/ui-strings/src/main/res/values/strings_tchap.xml, vector/src/main/java/fr/gouv/tchap/features/expired/ExpiredAccountActivity.kt, vector/src/main/res/layout/activity_tchap_expired.xml
Fix #1035 
|Before|After|
|-|-|
|![image](https://github.com/tchapgouv/tchap-android/assets/1191674/fbd97d30-b1bc-4d52-b6d6-072f8cafe072)|<img width="1313" alt="image" src="https://github.com/tchapgouv/tchap-android/assets/1191674/4370f41c-f0a2-44f6-a5d6-e2f7e6035908">|
=> Update expired account screen

tools/release/sign_all_apks_yubi.sh, tools/release/sign_apk_yubi.sh
=> Add script to sign apks with yubikey

changelog.d/1043.feature, vector-config/src/tchap/res/values/config-features.xml
https://github.com/tchapgouv/tchap-product/issues/316
- Step 1
- Step 2
- Step ...
=> Enable VoIP for all instances

vector-config/src/tchap/res/values/config-features.xml
=> Enable voip for all homeservers

changelog.d/906.bugfix, vector/src/main/java/im/vector/app/features/settings/VectorSettingsUrls.kt
Workaround to bypass this issue https://github.com/tchapgouv/tchap-android/issues/906#issuecomment-2144787186
#906 
- Step 1
- Step 2
- Step ...
=> Update faq url

changelog.d/1064.feature, towncrier.toml, vector-app/build.gradle, vector-config/src/tchap/res/values/config-features.xml
=> Enable voip except on finances homeserver

TCHAP_CHANGES.md, changelog.d/1070.wip, towncrier.toml, vector-app/build.gradle, vector/build.gradle, vector/src/withdmvoip/java/im/vector/app/features/call/webrtc/WebRtcCallManager.kt
Debug mode in webrtc is enabled
- Step 1
- Step 2
- Step ...
=> Enable webrtc debug mode

changelog.d/1071.wip, vector/src/withdmvoip/java/im/vector/app/features/call/webrtc/WebRtcCall.kt
Disable SSL verification for webrtc connection. related to https://groups.google.com/g/discuss-webrtc/c/4MmARU0XYqc/m/QppVNJiEAAAJ
- Step 1
- Step 2
- Step ...
=> bypass SSL verification in webrtc

TCHAP_CHANGES.md, changelog.d/1055.improvements, changelog.d/1071.wip, vector-app/build.gradle, vector/build.gradle, vector/src/withdmvoip/java/im/vector/app/features/call/webrtc/WebRtcCall.kt
#1055 
- Step 1
- Step 2
- Step ...
=> Support Audio call on Neo devices

changelog.d/1088.bugfix, vector/src/main/java/im/vector/app/features/analytics/DecryptionFailureTracker.kt, vector/src/main/java/im/vector/app/features/analytics/ReportedDecryptionFailurePersistence.kt
#1088 
- Step 1
- Step 2
- Step ...
=> Restore DecryptionFailureTracker to fix the crash on Android 5 and 6

changelog.d/1092.feature, vector-config/src/tchap/res/values/config-features.xml
#1078 
like #1079 
- Step 1
- Step 2
- Step ...
=> Enable visio for Finances instance

towncrier.toml, vector-app/build.gradle, vector-config/src/tchap/res/values/config-features.xml
=> Restore beta features

changelog.d/1107.improvements, library/ui-strings/src/main/res/values-fr/strings.xml, library/ui-strings/src/main/res/values-fr/strings_tchap.xml, library/ui-strings/src/main/res/values/strings.xml, library/ui-strings/src/main/res/values/strings_tchap.xml, vector/src/main/res/xml/vector_settings_notifications.xml
#1107 
- Step 1
- Step 2
- Step ...
=> Add description for account notification setting

changelog.d/1121.feature, vector-config/src/tchap/res/values/config-features.xml
#1121 
- Step 1
- Step 2
- Step ...
=> Enable visio for Education and Agent instances

towncrier.toml, vector-app/build.gradle, vector-config/src/tchap/res/values/config-features.xml
=> Upgrade version

vector/src/main/AndroidManifest.xml, vector/src/main/java/im/vector/app/core/services/CallAndroidService.kt, vector/src/withdmvoip/java/im/vector/app/features/call/VectorCallActivity.kt, vector/src/withvoip/java/im/vector/app/features/call/VectorCallActivity.kt
=> Restore android call service

changelog.d/1140.misc, towncrier.toml, vector-app/build.gradle, vector-config/src/main/java/im/vector/app/config/Config.kt
#1140 
- Step 1
- Step 2
- Step ...
=> Add analytics config to test server load

changelog.d/1142.misc, matrix-sdk-android/build.gradle
Upgrade realm-gradle-plugin to 10.19.0
- Step 1
- Step 2
- Step ...
=> Upgrade realm-gradle-plugin to 10.19.0

changelog.d/1145.misc, vector/src/main/java/im/vector/app/features/crypto/keys/KeysExporter.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt
=> Add password policy to export keys

changelog.d/1146.bugfix, towncrier.toml, vector-app/build.gradle, vector/src/withpinning/res/xml/network_security_config.xml
=> Add posthogdev exception

changelog.d/1154.misc, library/ui-strings/src/main/res/values-fr/strings.xml, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSplashFragment.kt, vector/src/main/res/layout/fragment_tchap_welcome.xml
=> Update sso button wording

changelog.d/1157.improvements, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/content/UploadContentWorker.kt
=> Increase image resolution

ELEMENT_CHANGES.md, changelog.d/1158.improvements, fastlane/metadata/android/en-US/changelogs/40106340.txt, matrix-sdk-android/build.gradle, vector-app/build.gradle, vector/src/main/java/im/vector/app/features/MainActivity.kt, vector/src/main/java/im/vector/app/features/pin/PinFragment.kt
=> Rebase against Element Android v1.6.34

changelog.d/1156.improvements, vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractSSOFtueAuthFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt
#1156 
- Step 1
- Step 2
- Step ...
=> Add login_hint parameter

matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/auth/AuthenticationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/Session.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/auth/DefaultAuthenticationService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/DefaultSession.kt, vector/src/main/java/im/vector/app/AutoRageShaker.kt, vector/src/main/java/im/vector/app/core/utils/ExternalApplicationsUtil.kt, vector/src/main/java/im/vector/app/features/auth/ReAuthState.kt, vector/src/main/java/im/vector/app/features/auth/ReAuthViewModel.kt, vector/src/main/java/im/vector/app/features/login/AbstractSSOLoginFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginActivity.kt, vector/src/main/java/im/vector/app/features/login/LoginFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginSignUpSignInSelectionFragment.kt, vector/src/main/java/im/vector/app/features/login/LoginViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/AbstractSSOFtueAuthFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthCombinedRegisterFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthSignUpSignInSelectionFragment.kt, vector/src/main/java/im/vector/app/features/rageshake/BugReportActivity.kt, vector/src/main/java/im/vector/app/features/rageshake/BugReportState.kt, vector/src/main/java/im/vector/app/features/rageshake/BugReportViewModel.kt, vector/src/main/java/im/vector/app/features/rageshake/BugReporter.kt
=> Support login_hint with UIA

.github/workflows/build.yml
=> Upgrade runner os version

changelog.d/1165.bugfix, towncrier.toml, vector-app/build.gradle, vector/src/main/java/im/vector/app/AutoRageShaker.kt
=> Fix crash on startup

vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt
Support login with a MAS
- Step 1
- Step 2
- Step ...
=> Support MAS login flow

changelog.d/1178.bugfix, vector/src/btchap/AndroidManifest.xml, vector/src/devTchap/AndroidManifest.xml, vector/src/tchap/AndroidManifest.xml
=> Add deep links verification

changelog.d/1184.improvements, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/permalinks/MatrixToConverter.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/permalinks/PermalinkService.kt, matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/util/StringUtils.kt
=> Support new permalinks from TchapX

changelog.d/1185.feature, library/ui-strings/src/main/res/values-fr/strings_tchap.xml, library/ui-strings/src/main/res/values/strings.xml, library/ui-strings/src/main/res/values/strings_tchap.xml, vector-config/src/main/java/im/vector/app/config/Config.kt, vector/src/main/java/fr/gouv/tchap/onboarding/TchapWeakPasswordException.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingAction.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewEvents.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewModel.kt, vector/src/main/java/im/vector/app/features/onboarding/OnboardingViewState.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthLoginFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthResetPasswordEmailEntryFragment.kt, vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt
=> Support MAS  flow on login by email and account registration.

changelog.d/1187.bugfix, dependencies.gradle, towncrier.toml, vector-app/build.gradle
```
Failed to execute the transaction: tId:-359317938 ClientTransaction{
tId:-359317938   transactionItems=[
tId:-359317938     LaunchActivityItem{activityToken=android.os.BinderProxy@4ca2f29,intent=Intent { xflg=0x4 cmp=fr.gouv.tchap.a/im.vector.app.features.home.room.detail.RoomDetailActivity (has extras) },ident=255924563,info=ActivityInfo{9c13d84 im.vector.app.features.home.room.detail.RoomDetailActivity},curConfig={1.0 208mcc1mnc [fr_FR] ldltr sw448dp w448dp h997dp 360dpi nrml long hdr widecg port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1008, 2244) mAppBounds=Rect(0, 0 - 1008, 2244) mMaxBounds=Rect(0, 0 - 1008, 2244) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} s.781 …
```
=> Min SDK 26
